name: Build Action

on:
  pull_request:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up xPack gcc riscv compiler
      uses: gregdavill/setup-riscv-gnu-toolchain@v2
    - run: make